name: "vergihesaplayici.com"

on:
  push:
    branches: master
    paths-ignore:
      - "**.md"
      - "logo"
      - ".github/dependabot.yml"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
        - name: "[SET UP] Checkout repo"
          uses: actions/checkout@master

        - name: "[SET UP] Set up Node"
          uses: actions/setup-node@master

        - name: "[SET UP] Install dependencies"
          run: npm install


        - name: "[QUALITY] Run unit tests"
          run: npm run test:unit
          env:
            VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}

        - name: "[QUALITY] Run E2E tests"
          uses: cypress-io/github-action@v1
          with:
            start: npm run serve
            wait-on: http://localhost:8080
            config-file: cypress.json
          env:
            CYPRESS_BASE_URL: http://localhost:8080
            VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}


        - name: "[DEPLOY] Build for production"
          run: npm run build
          env:
            VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}

        - name: "[DEPLOY] Deploy to Firebase"
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
